name: driver_drowsidetection
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2

  #camera
  camera: ^0.11.3
  permission_handler: ^12.0.1
  camera_windows: ^0.2.6+2
  camera_linux: ^0.0.8
  camera_macos: ^0.0.9
  flutter_blue_plus: ^1.31.15
  http: ^1.5.0
  dio: ^5.9.0
  image: ^4.5.4
  path_provider: ^2.1.5

  #alerts
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/welcome.jpg
    - lib/assets/welcome.png
    - lib/assets/sign.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
